### ISSUE TITLE
Could not locate that dashboard (id: Git-Performance)

### ISSUE THREAD

**Issue by jsmanrique** [dlumbrer/kbn_dashmenu_manager#1]
I have created a dashboard called `Git Performance` and added it to a `Git` menu entry as:
Title: Performance
Dashboard: Git Performance

When I click on it, I get the following error message on top of Kibiter:
`Could not locate that dashboard (id: Git-Performance)`

Any clue what is going on?

**Comment by dlumbrer** [comment]
I have fixed this bug in 062316fcd5c4d72c3c37a8625b09ae23f208af1f, it happens because I was storing the title (Kibana title, not our custom title), and the correct way is to store the id of the dashboard.

I'm updating the version of Kibiter in docker-hub in order to have this update.
